# Generated by Django 4.1 on 2022-09-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
