# Generated by Django 4.1 on 2022-09-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_todo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='audio',
            field=models.FileField(default='default.mp4', upload_to='audio_files'),
        ),
    ]
