# Generated by Django 4.1 on 2022-09-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_todo_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='audio',
            field=models.FileField(upload_to='audio_files'),
        ),
    ]
