# Generated by Django 4.1.1 on 2022-09-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_alter_todo_audio_delete_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='audio',
            field=models.FileField(default='default.mp3', upload_to='audio_files/'),
        ),
    ]
