# Generated by Django 4.1.1 on 2022-09-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_alter_todo_options_alter_todo_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='audio',
        ),
        migrations.AddField(
            model_name='todo',
            name='video',
            field=models.FileField(null=True, upload_to='video/%y'),
        ),
    ]
